MACHINE=
SCRIPT_NAME=elfmc9s12x
OUTPUT_FORMAT="elf32-mc9s12x"
TEXT_MEMORY=text
DATA_MEMORY=data
EEPROM_MEMORY=eeprom
ARCH=mc9s12x
MAXPAGESIZE=32
GENERIC_BOARD=yes
TEMPLATE_NAME=elf32
EXTRA_EM_FILE=mc9s12xelf

