MACHINE=
SCRIPT_NAME=elfmc9xgate
OUTPUT_FORMAT="elf32-mc9xgate"
TEXT_MEMORY=text
DATA_MEMORY=data
EEPROM_MEMORY=eeprom
ARCH=mc9xgate
MAXPAGESIZE=32
GENERIC_BOARD=yes
TEMPLATE_NAME=elf32
EXTRA_EM_FILE=mc9xgateelf

