MACHINE=
SCRIPT_NAME=elfxgate
OUTPUT_FORMAT="elf32-xgate"
TEXT_MEMORY=text
DATA_MEMORY=data
EEPROM_MEMORY=eeprom
ARCH=xgate
MAXPAGESIZE=32
GENERIC_BOARD=yes
TEMPLATE_NAME=elf32
EXTRA_EM_FILE=xgateelf

